# Generated by Django 2.2.1 on 2019-07-25 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_image', models.ImageField(blank=True, upload_to='users_pics')),
                ('user_isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=256)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('post_image', models.ImageField(blank=True, upload_to='posts_pics')),
                ('post_content', models.TextField()),
                ('post_tags', models.CharField(blank=True, max_length=256)),
                ('post_comment_count', models.IntegerField(blank=True, default=0)),
                ('post_status', models.CharField(max_length=256)),
                ('post_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post_cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_app.Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_content', models.TextField()),
                ('com_status', models.CharField(max_length=256)),
                ('com_date', models.DateField(auto_now_add=True)),
                ('com_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('com_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.Post')),
            ],
        ),
    ]
